### ISSUE TITLE
Iteration Plan for Sprint 3

### ISSUE THREAD

**Issue by domsec** [LujainKhalaf/SOEN341#151]
This plan capture our work in **Sprint 3**. This is a 3-week iteration. We will ship on **March 18, 2021**.

### Housekeeping

- [x] Issue Grooming - stories, features, task breakdown, reviews, categorization, assignment
- [x] Frequent Meetings - meeting minutes available
- [x] Plan for Sprint 4

### GitHub

- [x] Projects Board
- [x] Wiki - Iteration Plans, Meeting Minutes

### System

**Features**
- [x] Feed (Home) #98
- [x] Comments #114 #115
- [x] Create a Post (Enhanced) #137

### Misc

- [x] Refactor to MVC standard #127 
- [x] Architecture block diagram Wiki #135
- [x] Acceptance tests for all User Stories #136
