### ISSUE TITLE
Iteration Plan for Sprint 4

### ISSUE THREAD

**Issue by domsec** [LujainKhalaf/SOEN341#165]
This plan capture our work in **Sprint 4**. This is a 4-week iteration. We will ship on **April 16, 2021**.

### Housekeeping

- [x] Issue Grooming - stories, features, task breakdown, reviews, categorization, assignment
- [x] Frequent Meetings - meeting minutes available

### GitHub

- [x] Projects Board
- [x] Wiki - Iteration Plans, Meeting Minutes
    - [x] Coding / Naming conventions Wiki #153

### System

**Features**
- [x] Follower / Following modal (Profile page) #112

**Other**
- [x] Static analysis packages to CI/CD pipeline #158 
- [x] Unit tests #138
- [x] Functional tests #139

### Misc

- [x] Acceptance tests for all User Stories
- [x] Directory and package structure
    - Files with similar functionality are organized in packages
- [x] Quality of code - no clear code smells
